# Generated by Django 5.0.6 on 2024-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon_url", models.URLField()),
                ("bundle_count", models.IntegerField()),
                ("yday_avg_price", models.FloatField()),
                ("recent_price", models.FloatField()),
                ("current_min_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
